---
title: "IBER24"
author: "Javier Fernández-López & Valentin Lauret"
date: "2024-04-16"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
---

```{=html}
<style type="text/css">
.title {
  display: none;
}

.main-container {
  max-width: 1600px;
  margin-left: auto;
  margin-right: auto;
}

body {
text-align: justify
}

#getting-started img {
  margin-right: 10px;
}

</style>
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(tooltip_message = 'Click para copiar', tooltip_success = 'Hecho!',position = c('top', 'right'))
```
 
# Presentación

 En este espacio se encuentran los contenidos teóricos y prácticos para el taller **Inferencia Bayesiana en Ecología con R (IBER24)** que se impartirá en el Instituto de Investigación en Recursos Cinegéticos del 13 al 15 de mayo de 2024. Próximamente se irán incluyendo los materiales necesarios para la realización del curso